[package]
name="bens_aztec_testing"
type="contract"
authors = [ "benhooper.eth" ]
compiler_version = ">=0.18.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.52.0", directory = "noir-projects/aztec-nr/aztec" }
